import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from "./components/ReduxProvider";
import FCM from "./components/fcm";

export const metadata: Metadata = {
  title: "Cricket Admin Panel",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body >
        <ReduxProvider>
          {children}
          <FCM />
        </ReduxProvider>
      </body>
    </html>
  );
}

