import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from "./components/ReduxProvider";

export const metadata: Metadata = {
  title: "Cricket Admin Panel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body >
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}

