import type { Metadata } from "next";
import "./globals.css";
import AuthCheck from "./AuthCheck";   // <-- add this



export const metadata: Metadata = {
  title: "Cricket Admin Panel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body >
        <AuthCheck>{children}</AuthCheck>
      </body>
    </html>
  );
}
